"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const persons_1 = require("../controllers/persons");
const checkAddPerson_1 = require("../middlewares/checkAddPerson");
const checkErrorValidation_1 = require("../middlewares/checkErrorValidation");
const simulateLazy_1 = require("../middlewares/simulateLazy");
const validMongoId_1 = require("../utils/validMongoId");
const router = express_1.default.Router();
const { addNewPerson, getPerson, deletePerson, editPerson, addMorePersons, deletePersons, } = persons_1.personsController;
router.post("/", simulateLazy_1.simulateLazy, checkAddPerson_1.checkAddPerson, checkErrorValidation_1.checkErrorValidation, addNewPerson);
router.patch("/:id", simulateLazy_1.simulateLazy, checkAddPerson_1.checkAddPerson, checkErrorValidation_1.checkErrorValidation, editPerson);
router.get("/", simulateLazy_1.simulateLazy, getPerson);
router.get("/add", simulateLazy_1.simulateLazy, addMorePersons);
router.get("/delete", simulateLazy_1.simulateLazy, deletePersons);
router.delete("/:id", simulateLazy_1.simulateLazy, (0, validMongoId_1.mongoIdValidator)("id"), checkErrorValidation_1.checkErrorValidation, deletePerson);
exports.default = router;
